/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/pages/HomePage/Auth/Auth.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormAuth: typeof import('./src/components/pages/HomePage/Auth/components/FormAuth/FormAuth.vue')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    Header: typeof import('./src/components/layout/Header/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout/MainLayout.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestComp: typeof import('./src/components/pages/HomePage/TestComp/TestComp.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
